Fix Deserialisation of dependencies
coralogix/protofetch pull request #24
Opened 2022-05-27 09:35 UTC by mbedulli

2022-05-27 17:14 UTC, saraiva132 commented on src/model/protofetch.rs
> +    let new_lock_file = toml::from_str::<LockFile>(&(string_fmt)).unwrap();
No need for parenthesis in `string_fmt`

2022-05-27 17:16 UTC, saraiva132 commented on src/model/protofetch.rs
> +    #[serde(skip_serializing_if = "Vec::is_empty", default)]
So in principle this behavior should be propagated to other values in the `Descriptor` struct, would you like to do that or keep it as is in scope of this PR

2022-05-27 17:16 UTC, saraiva132 commented on src/model/protofetch.rs
> +    assert_eq!(lock_file, new_lock_file)
I am surprised that none of the other tests covered this, unlucky :/

2022-05-28 13:27 UTC, saraiva132 commented
@mbedulli great work on moving from `Vec` to `BtreeSet`. I do have some doubts. Do we care about maintaining order always or just when serializing ? I suppose that this way it will work without a custom serde (which eventually we will need ) where we could order things. I do not think we are paying any significant cost really. 

Alternatively, I would recommend you take a look at `IndexSet` from `https://lib.rs/crates/indexmap` for a well maintained perhaps more ergonomic Ordered set. Let me know your thoughts

2022-05-28 13:30 UTC, saraiva132 commented on src/fetch.rs
> +            Cache::RepoKind,
This looks a bit weird, I am not familiar with `AutoMock` but is this usage of `Cache::RepoKind` mandatory ?

2022-05-28 13:39 UTC, saraiva132 commented on src/proto_repository.rs
> +#[cfg_attr(test, automock)]
Really awesome to introduce mocks and improve the code modularity! 🙏 

This seems to look a bit cleaner 

```
use mockall::*;
use mockall::predicate::*;
....
#[automock]
 pub trait ProtoRepository {
...
}
```

2022-05-28 13:52 UTC, saraiva132 requested changes
Great work overall. Thank you for the introduction of mocking. I think we can make things a bit more elegant. `BtreeMap` is a great data type but other options might be more ergonomic. I believe we do not have a test that for a specific `Descriptor` makes sure it deterministically serializes a `protofetch.lock`by checking actual string result

2022-05-30 16:07 UTC, saraiva132 commented on src/model/protofetch.rs
> +impl PartialEq<Self> for LockedDependency {
This can automatically be derived with macros. Unless there is a specific reason to do so manually

2022-05-31 07:06 UTC, mbedulli commented on src/fetch.rs
> +            Cache::RepoKind,
resolved: Replace it with Box<dyn ProtoRepository>

2022-05-31 07:07 UTC, mbedulli commented on src/proto_repository.rs
> +#[cfg_attr(test, automock)]
The annotation `#[cfg_attr(test, automock)]` is needed since the mockall package is just a dev-dependencies

2022-05-31 08:57 UTC, saraiva132 approved these changes
LGTM. Thank you for your work and congrats on your first rust PR! :D

2022-05-31 09:54 UTC, merged